/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Auto-generated code. Do not edit.

package com.google.genai.types;

import com.google.auto.value.AutoValue;
import com.google.genai.JsonSerializable;
import com.google.gson.annotations.SerializedName;
import com.ryanharter.auto.value.gson.GenerateTypeAdapter;
import java.util.Optional;

/**
 * Code generated by the model that is meant to be executed, and the result returned to the model.
 * Generated when using the [FunctionDeclaration] tool and [FunctionCallingConfig] mode is set to
 * [Mode.CODE].
 */
@GenerateTypeAdapter
@AutoValue
public abstract class ExecutableCode extends JsonSerializable {
  /** Required. The code to be executed. */
  @SerializedName("code")
  public abstract Optional<String> code();

  /** Required. Programming language of the `code`. */
  @SerializedName("language")
  public abstract Optional<String> language();

  /** Instantiates a builder for ExecutableCode. */
  public static Builder builder() {
    return new AutoValue_ExecutableCode.Builder();
  }

  /** Creates a builder with the same values as this instance. */
  public abstract Builder toBuilder();

  /** Builder for ExecutableCode. */
  @AutoValue.Builder
  public abstract static class Builder {
    @SerializedName("code")
    public abstract Builder code(String code);

    @SerializedName("code")
    abstract Builder code(Optional<String> code);

    @SerializedName("language")
    public abstract Builder language(String language);

    @SerializedName("language")
    abstract Builder language(Optional<String> language);

    public abstract ExecutableCode build();
  }

  /** Deserializes a JSON string to a ExecutableCode object. */
  public static ExecutableCode fromJson(String jsonString) {
    return JsonSerializable.fromJsonString(jsonString, ExecutableCode.class);
  }
}
