/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Auto-generated code. Do not edit.

package com.google.genai.types;

import com.google.auto.value.AutoValue;
import com.google.genai.JsonSerializable;
import com.google.gson.annotations.SerializedName;
import com.ryanharter.auto.value.gson.GenerateTypeAdapter;
import java.util.Optional;

/** Response message for API call. */
@GenerateTypeAdapter
@AutoValue
public abstract class LiveServerMessage extends JsonSerializable {
  /** Sent in response to a `LiveClientSetup` message from the client. */
  @SerializedName("setupComplete")
  public abstract Optional<LiveServerSetupComplete> setupComplete();

  /** Content generated by the model in response to client messages. */
  @SerializedName("serverContent")
  public abstract Optional<LiveServerContent> serverContent();

  /**
   * Request for the client to execute the `function_calls` and return the responses with the
   * matching `id`s.
   */
  @SerializedName("toolCall")
  public abstract Optional<LiveServerToolCall> toolCall();

  /**
   * Notification for the client that a previously issued `ToolCallMessage` with the specified `id`s
   * should have been not executed and should be cancelled.
   */
  @SerializedName("toolCallCancellation")
  public abstract Optional<LiveServerToolCallCancellation> toolCallCancellation();

  /** Instantiates a builder for LiveServerMessage. */
  public static Builder builder() {
    return new AutoValue_LiveServerMessage.Builder();
  }

  /** Creates a builder with the same values as this instance. */
  public abstract Builder toBuilder();

  /** Builder for LiveServerMessage. */
  @AutoValue.Builder
  public abstract static class Builder {
    @SerializedName("setupComplete")
    public abstract Builder setupComplete(LiveServerSetupComplete setupComplete);

    @SerializedName("setupComplete")
    abstract Builder setupComplete(Optional<LiveServerSetupComplete> setupComplete);

    @SerializedName("serverContent")
    public abstract Builder serverContent(LiveServerContent serverContent);

    @SerializedName("serverContent")
    abstract Builder serverContent(Optional<LiveServerContent> serverContent);

    @SerializedName("toolCall")
    public abstract Builder toolCall(LiveServerToolCall toolCall);

    @SerializedName("toolCall")
    abstract Builder toolCall(Optional<LiveServerToolCall> toolCall);

    @SerializedName("toolCallCancellation")
    public abstract Builder toolCallCancellation(
        LiveServerToolCallCancellation toolCallCancellation);

    @SerializedName("toolCallCancellation")
    abstract Builder toolCallCancellation(
        Optional<LiveServerToolCallCancellation> toolCallCancellation);

    public abstract LiveServerMessage build();
  }

  /** Deserializes a JSON string to a LiveServerMessage object. */
  public static LiveServerMessage fromJson(String jsonString) {
    return JsonSerializable.fromJsonString(jsonString, LiveServerMessage.class);
  }
}
